on:
  workflow_dispatch:
  schedule:
    - cron: '15 0,2,4,6,8,10 * * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay/it1h-1@cron
        with:
          token: ${{ secrets.token }}
